### PR TITLE
Added Mod Config Menu support

### PR DESCRIPTION
**Pull request by BlueRaja**
Added support for [Mod Config Menu](https://steamcommunity.com/sharedfiles/filedetails/?id=667104300).

To test, subscribe to the above mod, then open the options under Options -> Mod Options

### CODE REVIEW

**Comment by davenonymous** [comment]
Two questions:
a) wouldn't a version utilizing the LW2 or its Toolbox be a better solution, since one can probably expect more people to have that.
b) This is a hard dependency on MCM, right? So the game/mod breaks for everyone who already has it installed and would need to add that? Is there a way to integrate this optionally?

**Comment by robojumper** [comment]
Long War Toolbox has a lot of compatibility issues, to the point where I just pulled the config menu component out of it [into a single mod](http://steamcommunity.com/sharedfiles/filedetails/?id=781296580) because I was annoyed.

There is also one minor limitation with LW Mod Options, it saves the settings into a XComGameState_Object. That's frequently brought up because people have to adjust it every time they start a new campaign.

MCM is optional by design. The mod contains the interfaces, but the MCM code doesn't do anything without MCM.

**Comment by BlueRaja** [comment]
@thraaawn Unlike LW2/Toolbox, MCM is a lightweight, non-conflicting, **completely optional** API specifically for options menus.  It will not break the mod for existing users.

MCM uses [a clever trick](https://github.com/andrewgu/ModConfigMenu/blob/master/documentation/config.md) to save configs under `Documents\My Games\XCOM2\XComGame\Config\`.  This has two benefits:
1. Users who don't want to download MCM can edit settings for all mods in one place _(I added a note about this at the top of the .ini file, in big letters)_
2. Unlike now, when the mod updates, users won't lose all their settings

So even if you don't want to use the MCM UI, there's still benefits to using its API.

**Comment by davenonymous** [comment]
Awesome! Thanks for the PR! Merging.
I'll update the workshop later today, currently busy.

**Comment by davenonymous** [comment]
I needed to add
```
[UnrealEd.EditorEngine]
+EditPackages=ModConfigMenuAPI
```
to build it. ¯\_(ツ)_/¯ 

~~And the Mod Settings menu stays empty and no ini is being created. Any idea what I might be doing wrong?~~ Never mind, I derped.

**Comment by BlueRaja** [comment]
Try setting a Log in `EnsureConfigExists()` to see if it's being called?  I'll take a look at it tonight.

**Comment by davenonymous** [comment]
I did that. Nothing changed... I still had the Workshop mod subscribed. All good now. Thanks again!

**Pull request merged**
